db:
    image: postgres:9.4
    environment:
        - POSTGRES_DB=choir
        - POSTGRES_USER=choir
        - POSTGRES_PASSWORD=choir

uwsgi:
    build: .
    volumes:
        - /media
    links:
        - db
    environment:
        - DEBUG=True

nginx:
    build: .
    volumes_from:
        - uwsgi
    links:
        - uwsgi
    ports:
        - '80:80'
    command: nginx
