services:
  minio:
    ports:
      - "9000:9000/tcp"

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /bin/sleep 2;
      /usr/bin/mc config host add minio http://minio:9000 admin admin123;
      /usr/bin/mc mb minio/media;
      /usr/bin/mc policy set download minio/media;
      exit 0;
      "

  django:
    ports:
      - "8000:8000/tcp"

  caddy:
    ports:
      - "80:8100/tcp"
