# Generated by Django 5.2.7 on 2025-10-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repertory', '0002_remove_usage_period_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('rehearsal', 'Rehearsal'), ('live', 'Live'), ('other', 'Other')], default='rehearsal', max_length=20, verbose_name='type')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='location')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='EventSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.CharField(blank=True, max_length=200, verbose_name='usage')),
                ('soloist', models.CharField(blank=True, max_length=200, verbose_name='soloist')),
                ('order', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('song', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repertory.song')),
            ],
            options={
                'verbose_name': 'event song',
                'verbose_name_plural': 'event songs',
                'ordering': ('order',),
                'indexes': [models.Index(fields=['event', 'order'], name='events_even_event_i_9e6853_idx')],
            },
        ),
    ]
