# Generated by Django 3.1.7 on 2021-03-20 13:01

import choir.repertory.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='number')),
                ('page', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='page')),
                ('score_number', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='score number')),
                ('tempo', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo')),
                ('composer', models.CharField(blank=True, max_length=200, verbose_name='composer')),
                ('lyrics_writer', models.CharField(blank=True, max_length=200, verbose_name='lyrics writer')),
                ('date_added', models.DateField(auto_now_add=True, db_index=True, null=True, verbose_name='date added')),
                ('date_changed', models.DateField(auto_now=True, db_index=True, null=True, verbose_name='date changed')),
                ('periods', models.ManyToManyField(blank=True, to='repertory.Period', verbose_name='periods')),
            ],
            options={
                'verbose_name': 'song',
                'verbose_name_plural': 'songs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'usage',
                'verbose_name_plural': 'usages',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to=choir.repertory.models.get_song_file_name, verbose_name='file')),
                ('type', models.CharField(choices=[('score', 'Score'), ('midi', 'Midi'), ('choir', 'Choir'), ('chords', 'Chords'), ('lyrics', 'Lyrics'), ('soprano', 'Soprano'), ('contralto', 'Contralto'), ('tenore', 'Tenore'), ('basso', 'Basso')], max_length=50, verbose_name='type')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repertory.song')),
            ],
            options={
                'verbose_name': 'song file',
                'verbose_name_plural': 'song files',
                'ordering': ('file',),
            },
        ),
        migrations.AddField(
            model_name='song',
            name='usages',
            field=models.ManyToManyField(blank=True, to='repertory.Usage', verbose_name='usages'),
        ),
    ]
