# Generated by Django 5.2.7 on 2025-10-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='periods',
        ),
        migrations.RemoveField(
            model_name='song',
            name='usages',
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='songfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Usage',
        ),
    ]
